/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React from 'react';
import { motion, Variants } from 'framer-motion';

interface DisclaimerScreenProps {
  onNavigate: (view: 'start' | 'contact') => void;
}

const DisclaimerScreen: React.FC<DisclaimerScreenProps> = ({ onNavigate }) => {
  const viewVariants: Variants = {
    initial: { opacity: 0, y: 15 },
    animate: { opacity: 1, y: 0, transition: { staggerChildren: 0.1, duration: 0.5, ease: 'easeInOut' } },
    exit: { opacity: 0, y: -15 },
  };
  
  const itemVariants: Variants = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' } },
  };

  return (
    <motion.div
      key="disclaimer-screen"
      className="w-screen min-h-[calc(100vh-61px)] bg-gray-50 p-4 sm:p-6 lg:p-8"
      variants={viewVariants}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      <div className="max-w-4xl mx-auto bg-white p-8 sm:p-12 rounded-2xl shadow-sm">
        <motion.div variants={itemVariants}>
            <h2 className="text-4xl sm:text-5xl font-serif font-bold text-gray-900 leading-tight">
                Disclaimer
            </h2>
            <p className="mt-2 text-sm text-gray-500">Last updated: October 26, 2024</p>
        </motion.div>
        
        <motion.div variants={itemVariants} className="mt-8 prose prose-lg max-w-none text-gray-600">
          <p>
            The information and services provided by the Photo Changer application are for informational and experimental purposes only. By using this application, you acknowledge and agree to the terms of this disclaimer.
          </p>

          <h3 className="text-2xl font-serif font-semibold text-gray-800 mt-6">1. Technology Demonstration</h3>
          <p>
            Photo Changer is a technology demonstration designed to showcase the capabilities of generative AI. It is not a commercial product and should not be relied upon for professional or critical applications. The features and functionality may change without notice.
          </p>

          <h3 className="text-2xl font-serif font-semibold text-gray-800 mt-6">2. Accuracy of Generated Content</h3>
          <p>
            The images and content generated by the AI are for illustrative purposes only. While we strive for high-quality results, we do not guarantee the accuracy, realism, or appropriateness of any generated content. The virtual try-on may not perfectly represent how a garment would fit in reality.
          </p>
          
          <h3 className="text-2xl font-serif font-semibold text-gray-800 mt-6">3. User Responsibility</h3>
          <p>
            You are solely responsible for the content you upload and the prompts you provide. You agree not to upload images or use prompts that infringe on copyright, violate privacy, or contain harmful or offensive material. We are not responsible for the consequences of the content you choose to create.
          </p>

          <h3 className="text-2xl font-serif font-semibold text-gray-800 mt-6">4. No Warranty and Limitation of Liability</h3>
          <p>
            This application is provided "as is," without any warranties of any kind, express or implied. The creators of Photo Changer will not be liable for any damages, whether direct, indirect, incidental, or consequential, arising from your use of or inability to use the application.
          </p>
        
          <h3 className="text-2xl font-serif font-semibold text-gray-800 mt-6">5. Contact</h3>
          <p>
            If you have any questions about this disclaimer, please <button onClick={() => onNavigate('contact')} className="text-indigo-600 hover:underline">contact us</button>.
          </p>
        </motion.div>

        <motion.div variants={itemVariants} className="text-center mt-12">
            <button
                onClick={() => onNavigate('start')}
                className="relative inline-flex items-center justify-center px-8 py-3 text-base font-semibold text-white bg-gray-900 rounded-md cursor-pointer group hover:bg-gray-700 transition-colors"
            >
                Start Creating
            </button>
        </motion.div>
      </div>
    </motion.div>
  );
};

export default DisclaimerScreen;